/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardOutreachRouteImport } from './routes/dashboard.outreach'
import { Route as DashboardOpportunitiesRouteImport } from './routes/dashboard.opportunities'
import { Route as DashboardMissionsRouteImport } from './routes/dashboard.missions'
import { Route as DashboardCoachRouteImport } from './routes/dashboard.coach'
import { Route as DashboardApplyRouteImport } from './routes/dashboard.apply'
import { Route as DashboardPlansIndexRouteImport } from './routes/dashboard.plans.index'
import { Route as DashboardPlansNewRouteImport } from './routes/dashboard.plans.new'
import { Route as DashboardPlansPlanIdRouteImport } from './routes/dashboard.plans.$planId'
import { Route as ApiPublicSubscribeRouteImport } from './routes/api/public/subscribe'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOutreachRoute = DashboardOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOpportunitiesRoute = DashboardOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMissionsRoute = DashboardMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoachRoute = DashboardCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplyRoute = DashboardApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansIndexRoute = DashboardPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansNewRoute = DashboardPlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlansPlanIdRoute = DashboardPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicSubscribeRoute = ApiPublicSubscribeRouteImport.update({
  id: '/api/public/subscribe',
  path: '/api/public/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/apply': typeof DashboardApplyRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/dashboard/missions': typeof DashboardMissionsRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/dashboard/plans/$planId': typeof DashboardPlansPlanIdRoute
  '/dashboard/plans/new': typeof DashboardPlansNewRoute
  '/dashboard/plans/': typeof DashboardPlansIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/apply': typeof DashboardApplyRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/dashboard/missions': typeof DashboardMissionsRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/dashboard/plans/$planId': typeof DashboardPlansPlanIdRoute
  '/dashboard/plans/new': typeof DashboardPlansNewRoute
  '/dashboard/plans': typeof DashboardPlansIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard/apply': typeof DashboardApplyRoute
  '/dashboard/coach': typeof DashboardCoachRoute
  '/dashboard/missions': typeof DashboardMissionsRoute
  '/dashboard/opportunities': typeof DashboardOpportunitiesRoute
  '/dashboard/outreach': typeof DashboardOutreachRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/public/subscribe': typeof ApiPublicSubscribeRoute
  '/dashboard/plans/$planId': typeof DashboardPlansPlanIdRoute
  '/dashboard/plans/new': typeof DashboardPlansNewRoute
  '/dashboard/plans/': typeof DashboardPlansIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/dashboard/apply'
    | '/dashboard/coach'
    | '/dashboard/missions'
    | '/dashboard/opportunities'
    | '/dashboard/outreach'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/paystack-webhook'
    | '/api/public/subscribe'
    | '/dashboard/plans/$planId'
    | '/dashboard/plans/new'
    | '/dashboard/plans/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/dashboard/apply'
    | '/dashboard/coach'
    | '/dashboard/missions'
    | '/dashboard/opportunities'
    | '/dashboard/outreach'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/public/paystack-webhook'
    | '/api/public/subscribe'
    | '/dashboard/plans/$planId'
    | '/dashboard/plans/new'
    | '/dashboard/plans'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/terms'
    | '/dashboard/apply'
    | '/dashboard/coach'
    | '/dashboard/missions'
    | '/dashboard/opportunities'
    | '/dashboard/outreach'
    | '/dashboard/profile'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/public/paystack-webhook'
    | '/api/public/subscribe'
    | '/dashboard/plans/$planId'
    | '/dashboard/plans/new'
    | '/dashboard/plans/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiPublicSubscribeRoute: typeof ApiPublicSubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/outreach': {
      id: '/dashboard/outreach'
      path: '/outreach'
      fullPath: '/dashboard/outreach'
      preLoaderRoute: typeof DashboardOutreachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/opportunities': {
      id: '/dashboard/opportunities'
      path: '/opportunities'
      fullPath: '/dashboard/opportunities'
      preLoaderRoute: typeof DashboardOpportunitiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/missions': {
      id: '/dashboard/missions'
      path: '/missions'
      fullPath: '/dashboard/missions'
      preLoaderRoute: typeof DashboardMissionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/coach': {
      id: '/dashboard/coach'
      path: '/coach'
      fullPath: '/dashboard/coach'
      preLoaderRoute: typeof DashboardCoachRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/apply': {
      id: '/dashboard/apply'
      path: '/apply'
      fullPath: '/dashboard/apply'
      preLoaderRoute: typeof DashboardApplyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plans/': {
      id: '/dashboard/plans/'
      path: '/plans'
      fullPath: '/dashboard/plans/'
      preLoaderRoute: typeof DashboardPlansIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plans/new': {
      id: '/dashboard/plans/new'
      path: '/plans/new'
      fullPath: '/dashboard/plans/new'
      preLoaderRoute: typeof DashboardPlansNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plans/$planId': {
      id: '/dashboard/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/dashboard/plans/$planId'
      preLoaderRoute: typeof DashboardPlansPlanIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/subscribe': {
      id: '/api/public/subscribe'
      path: '/api/public/subscribe'
      fullPath: '/api/public/subscribe'
      preLoaderRoute: typeof ApiPublicSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardApplyRoute: typeof DashboardApplyRoute
  DashboardCoachRoute: typeof DashboardCoachRoute
  DashboardMissionsRoute: typeof DashboardMissionsRoute
  DashboardOpportunitiesRoute: typeof DashboardOpportunitiesRoute
  DashboardOutreachRoute: typeof DashboardOutreachRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPlansPlanIdRoute: typeof DashboardPlansPlanIdRoute
  DashboardPlansNewRoute: typeof DashboardPlansNewRoute
  DashboardPlansIndexRoute: typeof DashboardPlansIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplyRoute: DashboardApplyRoute,
  DashboardCoachRoute: DashboardCoachRoute,
  DashboardMissionsRoute: DashboardMissionsRoute,
  DashboardOpportunitiesRoute: DashboardOpportunitiesRoute,
  DashboardOutreachRoute: DashboardOutreachRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPlansPlanIdRoute: DashboardPlansPlanIdRoute,
  DashboardPlansNewRoute: DashboardPlansNewRoute,
  DashboardPlansIndexRoute: DashboardPlansIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiPublicSubscribeRoute: ApiPublicSubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
